name: Build Examples

on:
  workflow_run:
    workflows: ["Build Docker"]
    types: [completed]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build-Matter:
    runs-on: ubuntu-latest
    container:
      image: espressif/esp-matter:latest

    strategy:
      matrix:
        targets:
        - {example: light, target: esp32c6, prefix: thread_matter, sdkconfig: sdkconfig.defaults.c6_thread}

    steps:
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git wget flex bison python3 python3-pip cmake ninja-build

      - name: Clone & Set Up ESP-IDF
        run: |
          git clone --recursive --depth 1 https://github.com/espressif/esp-idf.git /opt/esp-idf
          cd /opt/esp-idf
          ./install.sh
          echo "IDF_PATH=/opt/esp-idf" >> $GITHUB_ENV
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af

      - name: Clone ESP-Matter (Shallow Clone)
        run: |
          git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/espressif/esp-matter.git /opt/esp-matter
          echo "ESP_MATTER_PATH=/opt/esp-matter" >> $GITHUB_ENV
      

      - name: Build application
        run: |
          source $IDF_PATH/export.sh
          cd $ESP_MATTER_PATH/examples/${{ matrix.targets.example }}

          if [ "${{ matrix.targets.sdkconfig }}" != "" ]; then
            idf.py -D SDKCONFIG_DEFAULTS="${{ matrix.targets.sdkconfig }}" set-target ${{ matrix.targets.target }} build
          else
            idf.py set-target ${{ matrix.targets.target }} build
          fi

          cd build

          TARGET_CHIP=$(cat project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["target"])')
          APP_BIN=$(cat project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["app_bin"])')
          OUT_BIN="$GITHUB_WORKSPACE/images/$TARGET_CHIP"_${{ matrix.targets.prefix }}_"$APP_BIN"
          esptool.py --chip $TARGET_CHIP merge_bin -o $OUT_BIN $(cat flash_args | tr '\n' ' ')

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: build-images-${{ matrix.targets.target }}-${{ matrix.targets.prefix }}-${{ matrix.targets.example }}
          path: images/

  deploy:
    needs:
      - Build-Matter
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: espressif/esp-matter:latest

    steps:
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          pattern: build-images-*
          path: images/
          merge-multiple: true

      - name: Generate Launchpad Config
        run: |
          cd images/
          $ESP_MATTER_PATH/tools/launchpad/generate_launchpad_config.sh ${{ github.repository_owner }}
          tree -H '.' -L 1 --noreport -T 'ESP Matter Launchpad Artifacts' -shi --charset utf-8 -I "index.html" -o index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: images/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
